# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98299b5c5d441029046cbf191c026fd654352ec2ec80412f02a38d19c37bdfca657c61fad01ccc699e9113fc298fdba7be9da19cba0c9322fc9a15468773ad02

test:
  secret_key_base: a33ee4577acf71ef7e2fdd07efc404ff8cc2e18c5655552b8ffc627311bdb0ff6345d1de199793aff084a4fc38eedcd1c5149ec4a4b6330f0785e3823497ab26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
